# Generated by Django 5.2.16 on 2026-07-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
