# Generated by Django 5.2.16 on 2026-07-26 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_extraction_runs_and_pages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecandidate',
            name='decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercisecandidate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisecandidate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exercise_candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
