# Generated by Django 5.2.16 on 2026-07-26 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_exercisecandidate_decision_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCandidateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('published', 'Published'), ('deprecated', 'Deprecated')], max_length=32)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('published', 'Published'), ('deprecated', 'Deprecated')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='workouts.exercisecandidate')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_candidate_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decided_at', '-id'],
            },
        ),
    ]
