# Generated by Django 5.2.16 on 2026-07-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_exercisecandidatedecision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisecandidate',
            options={'ordering': ['normalized_name', 'id'], 'permissions': [('review_exercisecandidate', 'Can review exercise candidates')]},
        ),
    ]
