# Generated by Django 5.2.16 on 2026-07-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_exercisecandidate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty_level',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='unspecified', max_length=32),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_requirement',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('none', 'None'), ('minimal', 'Minimal'), ('standard_gym', 'Standard gym'), ('specialized', 'Specialized')], default='unspecified', max_length=32),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('push', 'Push'), ('pull', 'Pull'), ('hinge', 'Hinge'), ('squat', 'Squat'), ('lunge', 'Lunge'), ('carry', 'Carry'), ('rotation', 'Rotation'), ('core', 'Core'), ('mobility', 'Mobility')], default='unspecified', max_length=32),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_body_area',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('full_body', 'Full body'), ('upper_body', 'Upper body'), ('lower_body', 'Lower body'), ('core', 'Core'), ('shoulders', 'Shoulders'), ('hips', 'Hips'), ('back', 'Back'), ('chest', 'Chest'), ('legs', 'Legs')], default='unspecified', max_length=32),
        ),
    ]
