# Generated by Django 5.2.16 on 2026-07-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_exercise_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='coaching_cues',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='common_mistakes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='execution_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='prescription_endurance',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exercise',
            name='prescription_hypertrophy',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exercise',
            name='prescription_strength',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exercise',
            name='safety_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='setup_steps',
            field=models.TextField(blank=True),
        ),
    ]
