# Generated by Django 5.2.16 on 2026-07-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_exercise_coaching_cues_exercise_common_mistakes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('diagram', 'Diagram'), ('other', 'Other')], default='image', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='exercise_media/')),
                ('external_url', models.URLField(blank=True)),
                ('license_name', models.CharField(max_length=200)),
                ('attribution_text', models.CharField(blank=True, max_length=300)),
                ('rights_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='workouts.exercise')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
