# Generated by Django 5.2.16 on 2026-07-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_exercisemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='challenge_duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='challenge_focus_area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='duration_band',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='short', max_length=16),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='plan_type',
            field=models.CharField(choices=[('single_session', 'Single session'), ('challenge', 'Challenge'), ('program', 'Program')], default='single_session', max_length=32),
        ),
    ]
