# Generated by Django 5.2.16 on 2026-07-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_workoutplan_challenge_duration_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutChallengeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('focus_area', models.CharField(blank=True, max_length=120)),
                ('target_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_days', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='workoutplanitem',
            name='challenge_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='workouts.workoutchallengeday'),
        ),
        migrations.AddConstraint(
            model_name='workoutchallengeday',
            constraint=models.UniqueConstraint(fields=('plan', 'day_number'), name='unique_challenge_day_number_per_plan'),
        ),
    ]
