# Generated by Django 5.2.16 on 2026-07-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_workoutchallengeday_workoutplanitem_challenge_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlanPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('focus_area', models.CharField(blank=True, max_length=120)),
                ('week_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('week_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['phase_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'phase_number'), name='unique_phase_number_per_plan')],
            },
        ),
    ]
