# Generated by Django 5.2.16 on 2026-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_workoutplanphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('movement_preparation', 'Movement preparation'), ('calisthenics', 'Calisthenics'), ('strength', 'Strength'), ('skill_practice', 'Skill practice'), ('plyometric_power', 'Plyometric and power'), ('conditioning', 'Conditioning'), ('mobility_flexibility', 'Mobility and flexibility'), ('core_stability', 'Core stability'), ('balance_coordination', 'Balance and coordination'), ('post_workout_regeneration', 'Post-workout regeneration')], max_length=64),
        ),
    ]
