# Generated by Django 5.2.16 on 2026-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_alter_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration_fit',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('short', 'Short session'), ('medium', 'Medium session'), ('long', 'Long session')], default='unspecified', max_length=16),
        ),
    ]
