# Generated by Django 5.2.16 on 2026-07-25 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=200)),
                ('target_id', models.CharField(max_length=64)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs changes')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
